project:
  type: website

website:
  title: "Oscar Su"
  navbar:
    title: false
    background: secondary
    collapse-below: sm
    left:
      - href: index.qmd
        text: About

format:
  html:
    theme:
      - darkly
      - styles.scss
    toc: false



