project:
  type: website

website:
  title: "Oscar Su"
  navbar:
    title: false
    background: secondary
    collapse-below: sm
    left:
      - href: index.qmd
        text: About
      - href: projects.qmd
        text: Projects
      - href: games.qmd
        text: Games
    right:
      - text: "Oscar Su's Personal Website" # will need to disable hover effect
  search: false

format:
  html:
    theme:
      - darkly
      - styles.scss
    toc: false
    
execute: 
  freeze: auto
